version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): update"
    open-pull-requests-limit: 5
    target-branch: "main"
    rebase-strategy: "auto"
  - package-ecosystem: "yarn"
    directory: "/app"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): update"
    open-pull-requests-limit: 5
    target-branch: "main"
    rebase-strategy: "auto"
  - package-ecosystem: "yarn"
    directory: "/server"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): update"
    open-pull-requests-limit: 5
    target-branch: "main"
    rebase-strategy: "auto"