compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.0.2.cjs

packageExtensions:
  "@fastify/websocket@*":
    dependencies:
      "@types/ws": "^8.18.1"
