global:
  scrape_interval: 20s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "dev.timescalecreator.org:9093"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 20s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "tsclocal"
    scrape_interval: 20s
    static_configs:
      - targets: ["dev.timescalecreator.org:3000"]

remote_write:
  - url: "https://prometheus-prod-56-prod-us-east-2.grafana.net/api/prom/push"
    basic_auth:
      username: "__GRAFANA_USERID__"
      password: "__GRAFANA_PSWD__"
