export enum AdminRecaptchaActions {
  ADMIN_FETCH_USERS = "ADMIN_FETCH_USERS",
  ADMIN_FETCH_ALL_PRIVATE_OFFICIAL_DATAPACKS = "ADMIN_FETCH_ALL_PRIVATE_OFFICIAL_DATAPACKS",
  ADMIN_FETCH_OFFICIAL_DATAPACK = "ADMIN_FETCH_OFFICIAL_DATAPACK",
  ADMIN_CREATE_USER = "ADMIN_CREATE_USER",
  ADMIN_DELETE_USER = "ADMIN_DELETE_USER",
  ADMIN_DELETE_USER_DATAPACKS = "ADMIN_DELETE_USER_DATAPACKS",
  ADMIN_UPLOAD_OFFICIAL_DATAPACK = "ADMIN_UPLOAD_OFFICIAL_DATAPACK",
  ADMIN_DELETE_OFFICIAL_DATAPACK = "ADMIN_DELETE_OFFICIAL_DATAPACK",
  ADMIN_FETCH_USER_DATAPACKS = "ADMIN_FETCH_USER_DATAPACKS",
  ADMIN_ADD_USERS_TO_WORKSHOP = "ADMIN_ADD_USERS_TO_WORKSHOP",
  ADMIN_CREATE_WORKSHOP = "ADMIN_CREATE_WORKSHOP",
  ADMIN_EDIT_WORKSHOP = "ADMIN_EDIT_WORKSHOP",
  ADMIN_DELETE_WORKSHOP = "ADMIN_DELETE_WORKSHOP",
  ADMIN_EDIT_USER = "ADMIN_EDIT_USER",
  ADMIN_UPDATE_DATAPACK_PRIORITY = "ADMIN_UPDATE_DATAPACK_PRIORITY",
  ADMIN_UPLOAD_DATAPACK_TO_WORKSHOP = "ADMIN_UPLOAD_DATAPACK_TO_WORKSHOP",
  ADMIN_ADD_OFFICIAL_DATAPACK_TO_WORKSHOP = "ADMIN_ADD_OFFICIAL_DATAPACK_TO_WORKSHOP",
  ADMIN_EDIT_OFFICIAL_DATAPACK = "ADMIN_EDIT_OFFICIAL_DATAPACK",
  ADMIN_UPLOAD_FILES_TO_WORKSHOP = "ADMIN_UPLOAD_FILES_TO_WORKSHOP",
  ADMIN_UPLOAD_COVER_PICTURE_TO_WORKSHOP = "ADMIN_UPLOAD_COVER_PICTURE_TO_WORKSHOP",
  ADMIN_DELETE_DATAPACK_COMMENT = "ADMIN_DELETE_DATAPACK_COMMENT"
}

export enum WorkshopRecaptchaActions {
  WORKSHOP_EDIT_DATAPACK_METADATA = "WORKSHOP_EDIT_DATAPACK_METADATA",
  WORKSHOP_DOWNLOAD_DATAPACK = "WORKSHOP_DOWNLOAD_DATAPACK",
  WORKSHOP_DOWNLOAD_FILE = "WORKSHOP_DOWNLOAD_FILE"
}

export enum UserRecaptchaActions {
  USER_FETCH_SINGLE_DATAPACK = "USER_FETCH_SINGLE_DATAPACK",
  USER_DOWNLOAD_DATAPACK = "USER_DOWNLOAD_DATAPACK",
  USER_UPLOAD_DATAPACK = "USER_UPLOAD_DATAPACK",
  USER_DELETE_DATAPACK = "USER_DELETE_DATAPACK",
  USER_EDIT_DATAPACK_METADATA = "USER_EDIT_DATAPACK_METADATA",
  USER_FETCH_WORKSHOP_DATAPACK = "USER_FETCH_WORKSHOP_DATAPACK",
  USER_PRIVATE_DOWNLOAD_DATAPACK_FILES_ZIP = "USER_PRIVATE_DOWNLOAD_DATAPACK_FILES_ZIP",
  USER_PUBLIC_DOWNLOAD_DATAPACK_FILES_ZIP = "USER_PUBLIC_DOWNLOAD_DATAPACK_FILES_ZIP",
  USER_UPLOAD_DATAPACK_COMMENT = "USER_UPLOAD_DATAPACK_COMMENT",
  USER_REPORT_COMMENT = "USER_REPORT_COMMENT",
  USER_DELETE_COMMENT = "USER_DELETE_COMMENT"
}
