name: Security Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    name: Security Checks
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Local Bin
        run: |
          mkdir -p $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install TruffleHog
        run: |
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b $HOME/.local/bin

      - name: TruffleHog Secret Detection
        id: trufflehog
        continue-on-error: true
        run: |
          trufflehog git file://$(pwd) --only-verified --fail --github-actions > trufflehog-results.json 2>&1;

      - name: Scan Results Status
        if: steps.trufflehog.outcome == 'failure'
        run: |
          cat trufflehog-results.json;
          exit 1;
