name: Security Pipeline

on:
  push:
    branches:
      - pipeline-test
  pull_request:
    types: [opened, synchronize, reopened] # Runs on opening a pr, pushing to a pr, and reopening a pr
    branches:
      - pipeline-test

jobs:
  security:
    name: Security Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Truffle
        run: curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin

        # # Static Code Analysis with CodeQL
        # - name: Set up CodeQL
        #   uses: github/codeql-action/init@v2
        #   with:
        #     languages: 'javascript'
        
        # - name: Perform CodeQL Analysis
        #   uses: github/codeql-action/analyze@v2

        # # Dependency Vulnerability Scanning with Dependabot
        # - name: Dependabot Dependency Review
        #   uses: dependabot/dependabot-core@v1
        #   with:
        #     package-ecosystem: 'npm'
        #     directory: '/'
        #     target-branch: 'main'
        
      - name: TruffleHog Secret Detection
        id: trufflehog
        continue-on-error: true 
        run: |
          trufflehog git file://$(pwd) --only-verified --fail --github-actions > trufflehog-reults.json 2>&1;

      - name: Scan Results Status 
        if: steps.trufflehog.outcome == 'failure' 
        run: |
            cat trufflehog-reults.json;
            exit 1;

      # # DAST with OWASP ZAP
      # - name: OWASP ZAP Baseline Scan
      #   uses: zaproxy/action-baseline@v0.4.0
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     target: 'http://your-web-app-url'