name: Verify Translations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compare-json-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: yarn install

      - name: Verify Translations
        working-directory: server
        run: yarn build && yarn verify-translations